// @generated by gen_coralnpu_wrapper.py — DO NOT hand-edit.
// Vyges integration wrapper for the CoralNPU autonomous compute island.
// V1.5 tie-off-first: device masters / debug / SPI / GPIO tied; DDR-mem
// exported as a STANDARD AXI4 master m_axi_ddr_{aw,w,b,ar,r}* (bridged
// from the Chisel bundle internally); boot_addr in; wfi out.
// See socs/_ip/coralnpu-subsystem.yaml for the integration contract.

module coralnpu_island (
  input  wire        clk_i,
  input  wire        rst_ni,
  input  wire [31:0] boot_addr_i,
  output wire           m_axi_ddr_awvalid,
  output wire [31:0]    m_axi_ddr_awaddr,
  output wire [2:0]     m_axi_ddr_awprot,
  output wire           m_axi_ddr_awid,
  output wire [7:0]     m_axi_ddr_awlen,
  output wire [2:0]     m_axi_ddr_awsize,
  output wire [1:0]     m_axi_ddr_awburst,
  output wire           m_axi_ddr_awlock,
  output wire [3:0]     m_axi_ddr_awcache,
  input  wire           m_axi_ddr_wready,
  output wire           m_axi_ddr_wvalid,
  output wire [255:0]   m_axi_ddr_wdata,
  output wire           m_axi_ddr_wlast,
  output wire [31:0]    m_axi_ddr_wstrb,
  output wire           m_axi_ddr_bready,
  input  wire           m_axi_ddr_bvalid,
  input  wire [1:0]     m_axi_ddr_bresp,
  input  wire           m_axi_ddr_arready,
  output wire           m_axi_ddr_arvalid,
  output wire [31:0]    m_axi_ddr_araddr,
  output wire [2:0]     m_axi_ddr_arprot,
  output wire           m_axi_ddr_arid,
  output wire [7:0]     m_axi_ddr_arlen,
  output wire [2:0]     m_axi_ddr_arsize,
  output wire [1:0]     m_axi_ddr_arburst,
  output wire           m_axi_ddr_arlock,
  output wire [3:0]     m_axi_ddr_arcache,
  output wire           m_axi_ddr_rready,
  input  wire           m_axi_ddr_rvalid,
  input  wire [255:0]   m_axi_ddr_rdata,
  input  wire           m_axi_ddr_rid,
  input  wire [1:0]     m_axi_ddr_rresp,
  input  wire           m_axi_ddr_rlast,
  output wire [3:0]   m_axi_ddr_awqos,
  output wire [3:0]   m_axi_ddr_arqos,
  input  wire           m_axi_ddr_bid,
  input  wire         m_axi_ddr_awready,
  output wire        wfi_o
);

  // rst_ni intentionally unused: CoralNPUChiselSubsystem has no reset port (internal POR /
  // coralnpu-rst-sync). Kept on the wrapper for uniform clk/rst wiring.
  wire _unused_rst = rst_ni;

  // DDR-mem standard-AXI facade (Chisel bundle <-> aw*/w*/b*/ar*/r*)
  wire           m_axi_ddr_write_addr_valid;
  wire [31:0]    m_axi_ddr_write_addr_bits_addr;
  wire [2:0]     m_axi_ddr_write_addr_bits_prot;
  wire           m_axi_ddr_write_addr_bits_id;
  wire [7:0]     m_axi_ddr_write_addr_bits_len;
  wire [2:0]     m_axi_ddr_write_addr_bits_size;
  wire [1:0]     m_axi_ddr_write_addr_bits_burst;
  wire           m_axi_ddr_write_addr_bits_lock;
  wire [3:0]     m_axi_ddr_write_addr_bits_cache;
  wire           m_axi_ddr_write_data_ready;
  wire           m_axi_ddr_write_data_valid;
  wire [255:0]   m_axi_ddr_write_data_bits_data;
  wire           m_axi_ddr_write_data_bits_last;
  wire [31:0]    m_axi_ddr_write_data_bits_strb;
  wire           m_axi_ddr_write_resp_ready;
  wire           m_axi_ddr_write_resp_valid;
  wire [1:0]     m_axi_ddr_write_resp_bits_resp;
  wire           m_axi_ddr_read_addr_ready;
  wire           m_axi_ddr_read_addr_valid;
  wire [31:0]    m_axi_ddr_read_addr_bits_addr;
  wire [2:0]     m_axi_ddr_read_addr_bits_prot;
  wire           m_axi_ddr_read_addr_bits_id;
  wire [7:0]     m_axi_ddr_read_addr_bits_len;
  wire [2:0]     m_axi_ddr_read_addr_bits_size;
  wire [1:0]     m_axi_ddr_read_addr_bits_burst;
  wire           m_axi_ddr_read_addr_bits_lock;
  wire [3:0]     m_axi_ddr_read_addr_bits_cache;
  wire           m_axi_ddr_read_data_ready;
  wire           m_axi_ddr_read_data_valid;
  wire [255:0]   m_axi_ddr_read_data_bits_data;
  wire           m_axi_ddr_read_data_bits_id;
  wire [1:0]     m_axi_ddr_read_data_bits_resp;
  wire           m_axi_ddr_read_data_bits_last;
  assign m_axi_ddr_awvalid = m_axi_ddr_write_addr_valid;
  assign m_axi_ddr_awaddr = m_axi_ddr_write_addr_bits_addr;
  assign m_axi_ddr_awprot = m_axi_ddr_write_addr_bits_prot;
  assign m_axi_ddr_awid = m_axi_ddr_write_addr_bits_id;
  assign m_axi_ddr_awlen = m_axi_ddr_write_addr_bits_len;
  assign m_axi_ddr_awsize = m_axi_ddr_write_addr_bits_size;
  assign m_axi_ddr_awburst = m_axi_ddr_write_addr_bits_burst;
  assign m_axi_ddr_awlock = m_axi_ddr_write_addr_bits_lock;
  assign m_axi_ddr_awcache = m_axi_ddr_write_addr_bits_cache;
  assign m_axi_ddr_write_data_ready = m_axi_ddr_wready;
  assign m_axi_ddr_wvalid = m_axi_ddr_write_data_valid;
  assign m_axi_ddr_wdata = m_axi_ddr_write_data_bits_data;
  assign m_axi_ddr_wlast = m_axi_ddr_write_data_bits_last;
  assign m_axi_ddr_wstrb = m_axi_ddr_write_data_bits_strb;
  assign m_axi_ddr_bready = m_axi_ddr_write_resp_ready;
  assign m_axi_ddr_write_resp_valid = m_axi_ddr_bvalid;
  assign m_axi_ddr_write_resp_bits_resp = m_axi_ddr_bresp;
  assign m_axi_ddr_read_addr_ready = m_axi_ddr_arready;
  assign m_axi_ddr_arvalid = m_axi_ddr_read_addr_valid;
  assign m_axi_ddr_araddr = m_axi_ddr_read_addr_bits_addr;
  assign m_axi_ddr_arprot = m_axi_ddr_read_addr_bits_prot;
  assign m_axi_ddr_arid = m_axi_ddr_read_addr_bits_id;
  assign m_axi_ddr_arlen = m_axi_ddr_read_addr_bits_len;
  assign m_axi_ddr_arsize = m_axi_ddr_read_addr_bits_size;
  assign m_axi_ddr_arburst = m_axi_ddr_read_addr_bits_burst;
  assign m_axi_ddr_arlock = m_axi_ddr_read_addr_bits_lock;
  assign m_axi_ddr_arcache = m_axi_ddr_read_addr_bits_cache;
  assign m_axi_ddr_rready = m_axi_ddr_read_data_ready;
  assign m_axi_ddr_read_data_valid = m_axi_ddr_rvalid;
  assign m_axi_ddr_read_data_bits_data = m_axi_ddr_rdata;
  assign m_axi_ddr_read_data_bits_id = m_axi_ddr_rid;
  assign m_axi_ddr_read_data_bits_resp = m_axi_ddr_rresp;
  assign m_axi_ddr_read_data_bits_last = m_axi_ddr_rlast;
  assign m_axi_ddr_awqos = 4'b0;
  assign m_axi_ddr_arqos = 4'b0;
  wire _unused_axi = &{1'b0, m_axi_ddr_bid, m_axi_ddr_awready};

  CoralNPUChiselSubsystem u_coralnpu (
    .io_clk_i                                     (clk_i),
    .io_external_devices_i2c_master_a_valid       (),
    .io_external_devices_i2c_master_a_bits_opcode (),
    .io_external_devices_i2c_master_a_bits_size   (),
    .io_external_devices_i2c_master_a_bits_source (),
    .io_external_devices_i2c_master_a_bits_address (),
    .io_external_devices_i2c_master_a_bits_mask   (),
    .io_external_devices_i2c_master_a_bits_data   (),
    .io_external_devices_i2c_master_a_bits_user_rsvd (),
    .io_external_devices_i2c_master_a_bits_user_instr_type (),
    .io_external_devices_i2c_master_a_bits_user_cmd_intg (),
    .io_external_devices_i2c_master_d_ready       (),
    .io_external_devices_i2c_master_d_valid       ('0),
    .io_external_devices_i2c_master_d_bits_opcode ('0),
    .io_external_devices_i2c_master_d_bits_size   ('0),
    .io_external_devices_i2c_master_d_bits_source ('0),
    .io_external_devices_i2c_master_d_bits_sink   ('0),
    .io_external_devices_i2c_master_d_bits_data   ('0),
    .io_external_devices_i2c_master_d_bits_user_rsp_intg ('0),
    .io_external_devices_i2c_master_d_bits_error  ('0),
    .io_external_devices_uart1_a_valid            (),
    .io_external_devices_uart1_a_bits_opcode      (),
    .io_external_devices_uart1_a_bits_size        (),
    .io_external_devices_uart1_a_bits_source      (),
    .io_external_devices_uart1_a_bits_address     (),
    .io_external_devices_uart1_a_bits_mask        (),
    .io_external_devices_uart1_a_bits_data        (),
    .io_external_devices_uart1_a_bits_user_rsvd   (),
    .io_external_devices_uart1_a_bits_user_instr_type (),
    .io_external_devices_uart1_a_bits_user_cmd_intg (),
    .io_external_devices_uart1_d_ready            (),
    .io_external_devices_uart1_d_valid            ('0),
    .io_external_devices_uart1_d_bits_opcode      ('0),
    .io_external_devices_uart1_d_bits_size        ('0),
    .io_external_devices_uart1_d_bits_source      ('0),
    .io_external_devices_uart1_d_bits_sink        ('0),
    .io_external_devices_uart1_d_bits_data        ('0),
    .io_external_devices_uart1_d_bits_user_rsp_intg ('0),
    .io_external_devices_uart1_d_bits_error       ('0),
    .io_external_devices_uart0_a_valid            (),
    .io_external_devices_uart0_a_bits_opcode      (),
    .io_external_devices_uart0_a_bits_size        (),
    .io_external_devices_uart0_a_bits_source      (),
    .io_external_devices_uart0_a_bits_address     (),
    .io_external_devices_uart0_a_bits_mask        (),
    .io_external_devices_uart0_a_bits_data        (),
    .io_external_devices_uart0_a_bits_user_rsvd   (),
    .io_external_devices_uart0_a_bits_user_instr_type (),
    .io_external_devices_uart0_a_bits_user_cmd_intg (),
    .io_external_devices_uart0_d_ready            (),
    .io_external_devices_uart0_d_valid            ('0),
    .io_external_devices_uart0_d_bits_opcode      ('0),
    .io_external_devices_uart0_d_bits_size        ('0),
    .io_external_devices_uart0_d_bits_source      ('0),
    .io_external_devices_uart0_d_bits_sink        ('0),
    .io_external_devices_uart0_d_bits_data        ('0),
    .io_external_devices_uart0_d_bits_user_rsp_intg ('0),
    .io_external_devices_uart0_d_bits_error       ('0),
    .io_external_devices_sram_a_valid             (),
    .io_external_devices_sram_a_bits_opcode       (),
    .io_external_devices_sram_a_bits_size         (),
    .io_external_devices_sram_a_bits_source       (),
    .io_external_devices_sram_a_bits_address      (),
    .io_external_devices_sram_a_bits_mask         (),
    .io_external_devices_sram_a_bits_data         (),
    .io_external_devices_sram_a_bits_user_rsvd    (),
    .io_external_devices_sram_a_bits_user_instr_type (),
    .io_external_devices_sram_a_bits_user_cmd_intg (),
    .io_external_devices_sram_d_ready             (),
    .io_external_devices_sram_d_valid             ('0),
    .io_external_devices_sram_d_bits_opcode       ('0),
    .io_external_devices_sram_d_bits_size         ('0),
    .io_external_devices_sram_d_bits_source       ('0),
    .io_external_devices_sram_d_bits_sink         ('0),
    .io_external_devices_sram_d_bits_data         ('0),
    .io_external_devices_sram_d_bits_user_rsp_intg ('0),
    .io_external_devices_sram_d_bits_error        ('0),
    .io_external_devices_rom_a_valid              (),
    .io_external_devices_rom_a_bits_opcode        (),
    .io_external_devices_rom_a_bits_size          (),
    .io_external_devices_rom_a_bits_source        (),
    .io_external_devices_rom_a_bits_address       (),
    .io_external_devices_rom_a_bits_mask          (),
    .io_external_devices_rom_a_bits_data          (),
    .io_external_devices_rom_a_bits_user_rsvd     (),
    .io_external_devices_rom_a_bits_user_instr_type (),
    .io_external_devices_rom_a_bits_user_cmd_intg (),
    .io_external_devices_rom_d_ready              (),
    .io_external_devices_rom_d_valid              ('0),
    .io_external_devices_rom_d_bits_opcode        ('0),
    .io_external_devices_rom_d_bits_size          ('0),
    .io_external_devices_rom_d_bits_source        ('0),
    .io_external_devices_rom_d_bits_sink          ('0),
    .io_external_devices_rom_d_bits_data          ('0),
    .io_external_devices_rom_d_bits_user_rsp_intg ('0),
    .io_external_devices_rom_d_bits_error         ('0),
    .io_external_ports_spim_flash_mosi            (),
    .io_external_ports_gpio_i                     ('0),
    .io_external_ports_gpio_en_o                  (),
    .io_external_ports_spim_clk_i                 ('0),
    .io_external_ports_spim_mosi                  (),
    .io_external_ports_spi_mosi                   ('0),
    .io_external_ports_dm_rsp_bits_op             (),
    .io_external_ports_dm_rsp_bits_data           (),
    .io_external_ports_dm_rsp_ready               ('0),
    .io_external_ports_dm_rsp_valid               (),
    .io_external_ports_dm_req_bits_op             ('0),
    .io_external_ports_dm_req_bits_data           ('0),
    .io_external_ports_dm_req_ready               (),
    .io_external_ports_dm_req_valid               ('0),
    .io_external_ports_boot_addr                  (boot_addr_i),
    .io_external_ports_te                         ('0),
    .io_external_ports_wfi                        (wfi_o),
    .io_ddr_ctrl_axi_write_addr_ready             ('0),
    .io_ddr_ctrl_axi_write_addr_valid             (),
    .io_ddr_ctrl_axi_write_addr_bits_addr         (),
    .io_ddr_ctrl_axi_write_addr_bits_prot         (),
    .io_ddr_ctrl_axi_write_addr_bits_id           (),
    .io_ddr_ctrl_axi_write_addr_bits_len          (),
    .io_ddr_ctrl_axi_write_addr_bits_size         (),
    .io_ddr_ctrl_axi_write_addr_bits_burst        (),
    .io_ddr_ctrl_axi_write_addr_bits_lock         (),
    .io_ddr_ctrl_axi_write_addr_bits_cache        (),
    .io_ddr_ctrl_axi_write_data_ready             ('0),
    .io_ddr_ctrl_axi_write_data_valid             (),
    .io_ddr_ctrl_axi_write_data_bits_data         (),
    .io_ddr_ctrl_axi_write_data_bits_last         (),
    .io_ddr_ctrl_axi_write_data_bits_strb         (),
    .io_ddr_ctrl_axi_write_resp_ready             (),
    .io_ddr_ctrl_axi_write_resp_valid             ('0),
    .io_ddr_ctrl_axi_write_resp_bits_id           ('0),
    .io_ddr_ctrl_axi_write_resp_bits_resp         ('0),
    .io_ddr_ctrl_axi_read_addr_ready              ('0),
    .io_ddr_ctrl_axi_read_addr_valid              (),
    .io_ddr_ctrl_axi_read_addr_bits_addr          (),
    .io_ddr_ctrl_axi_read_addr_bits_prot          (),
    .io_ddr_ctrl_axi_read_addr_bits_id            (),
    .io_ddr_ctrl_axi_read_addr_bits_len           (),
    .io_ddr_ctrl_axi_read_addr_bits_size          (),
    .io_ddr_ctrl_axi_read_addr_bits_burst         (),
    .io_ddr_ctrl_axi_read_addr_bits_lock          (),
    .io_ddr_ctrl_axi_read_addr_bits_cache         (),
    .io_ddr_ctrl_axi_read_data_ready              (),
    .io_ddr_ctrl_axi_read_data_valid              ('0),
    .io_ddr_ctrl_axi_read_data_bits_data          ('0),
    .io_ddr_ctrl_axi_read_data_bits_id            ('0),
    .io_ddr_ctrl_axi_read_data_bits_resp          ('0),
    .io_ddr_ctrl_axi_read_data_bits_last          ('0),
    .io_ddr_mem_axi_write_addr_valid              (m_axi_ddr_write_addr_valid),
    .io_ddr_mem_axi_write_addr_bits_addr          (m_axi_ddr_write_addr_bits_addr),
    .io_ddr_mem_axi_write_addr_bits_prot          (m_axi_ddr_write_addr_bits_prot),
    .io_ddr_mem_axi_write_addr_bits_id            (m_axi_ddr_write_addr_bits_id),
    .io_ddr_mem_axi_write_addr_bits_len           (m_axi_ddr_write_addr_bits_len),
    .io_ddr_mem_axi_write_addr_bits_size          (m_axi_ddr_write_addr_bits_size),
    .io_ddr_mem_axi_write_addr_bits_burst         (m_axi_ddr_write_addr_bits_burst),
    .io_ddr_mem_axi_write_addr_bits_lock          (m_axi_ddr_write_addr_bits_lock),
    .io_ddr_mem_axi_write_addr_bits_cache         (m_axi_ddr_write_addr_bits_cache),
    .io_ddr_mem_axi_write_data_ready              (m_axi_ddr_write_data_ready),
    .io_ddr_mem_axi_write_data_valid              (m_axi_ddr_write_data_valid),
    .io_ddr_mem_axi_write_data_bits_data          (m_axi_ddr_write_data_bits_data),
    .io_ddr_mem_axi_write_data_bits_last          (m_axi_ddr_write_data_bits_last),
    .io_ddr_mem_axi_write_data_bits_strb          (m_axi_ddr_write_data_bits_strb),
    .io_ddr_mem_axi_write_resp_ready              (m_axi_ddr_write_resp_ready),
    .io_ddr_mem_axi_write_resp_valid              (m_axi_ddr_write_resp_valid),
    .io_ddr_mem_axi_write_resp_bits_resp          (m_axi_ddr_write_resp_bits_resp),
    .io_ddr_mem_axi_read_addr_ready               (m_axi_ddr_read_addr_ready),
    .io_ddr_mem_axi_read_addr_valid               (m_axi_ddr_read_addr_valid),
    .io_ddr_mem_axi_read_addr_bits_addr           (m_axi_ddr_read_addr_bits_addr),
    .io_ddr_mem_axi_read_addr_bits_prot           (m_axi_ddr_read_addr_bits_prot),
    .io_ddr_mem_axi_read_addr_bits_id             (m_axi_ddr_read_addr_bits_id),
    .io_ddr_mem_axi_read_addr_bits_len            (m_axi_ddr_read_addr_bits_len),
    .io_ddr_mem_axi_read_addr_bits_size           (m_axi_ddr_read_addr_bits_size),
    .io_ddr_mem_axi_read_addr_bits_burst          (m_axi_ddr_read_addr_bits_burst),
    .io_ddr_mem_axi_read_addr_bits_lock           (m_axi_ddr_read_addr_bits_lock),
    .io_ddr_mem_axi_read_addr_bits_cache          (m_axi_ddr_read_addr_bits_cache),
    .io_ddr_mem_axi_read_data_ready               (m_axi_ddr_read_data_ready),
    .io_ddr_mem_axi_read_data_valid               (m_axi_ddr_read_data_valid),
    .io_ddr_mem_axi_read_data_bits_data           (m_axi_ddr_read_data_bits_data),
    .io_ddr_mem_axi_read_data_bits_id             (m_axi_ddr_read_data_bits_id),
    .io_ddr_mem_axi_read_data_bits_resp           (m_axi_ddr_read_data_bits_resp),
    .io_ddr_mem_axi_read_data_bits_last           (m_axi_ddr_read_data_bits_last)
  );

endmodule
