#!/usr/bin/env python3
"""Generate coralnpu_island.sv — a clean Vyges integration wrapper around the
elaborated CoralNPUChiselSubsystem (autonomous compute island).

Mirrors the rocket_tile_tlul approach: wrap the messy 181-port Chisel top in a
small surface the soc-generator can wire uniformly. V1.5 = tie-off-first:
  - drive io_clk_i from clk_i; expose rst_ni (unused at this boundary — the
    subsystem resets internally via coralnpu-rst-sync — kept for uniform wiring)
  - boot_addr_i  -> io_external_ports_boot_addr (firmware reset vector)
  - m_axi_ddr_*  <-> io_ddr_mem_axi_*  (256-bit AXI4 master, exported to board DRAM)
  - wfi_o        <- io_external_ports_wfi (status)
  - EVERYTHING ELSE tied off: 5 device masters (rom/sram/uart0/uart1/i2c),
    ddr_ctrl_axi, debug dm, SPI slave/master, GPIO, te. Inputs -> 0; outputs open.

Usage: gen_coralnpu_wrapper.py <coralnpu-Subsystem.sv> <out coralnpu_island.sv>
"""
import re, sys

SRC, OUT = sys.argv[1], sys.argv[2]
TOP = "CoralNPUChiselSubsystem"

text = open(SRC).read()
m = re.search(r"^module %s\b" % TOP, text, re.M)
assert m, "top module not found"
body = text[m.start():]
hdr = body[: body.index(");") + 2]

# parse port lines: <dir> [width] name
ports = []
for line in hdr.splitlines():
    pm = re.match(r"\s*(input|output|inout)\s+(\[[^\]]+\]\s*)?\s*(io_[A-Za-z0-9_]+)", line)
    if pm:
        ports.append((pm.group(1), (pm.group(2) or "").strip(), pm.group(3)))

def zero(width):
    return "1'b0" if not width else "%s'b0" % "" if False else ("'0")

# wrapper ports + instance connections
wports = ["  input  wire        clk_i",
          "  input  wire        rst_ni",            # unused (internal reset) — uniform wiring
          "  input  wire [31:0] boot_addr_i",
          "  output wire        wfi_o"]
conns = []
ddr = []   # exported m_axi_ddr_* wrapper ports
for d, w, name in ports:
    if name == "io_clk_i":
        conns.append((name, "clk_i")); continue
    if name == "io_external_ports_boot_addr":
        conns.append((name, "boot_addr_i")); continue
    if name == "io_external_ports_wfi":
        conns.append((name, "wfi_o")); continue
    if name.startswith("io_ddr_mem_axi_"):
        sig = "m_axi_ddr_" + name[len("io_ddr_mem_axi_"):]
        ddr.append("  %-6s wire %-9s %s" % (d, w, sig))
        conns.append((name, sig)); continue
    # tie-off everything else
    if d == "input":
        conns.append((name, "'0"))
    else:  # output we don't use -> leave open
        conns.append((name, ""))

wports = wports[:3] + ddr + [wports[3]]  # clk/rst/boot, then ddr exports, then wfi

with open(OUT, "w") as f:
    f.write("// @generated by gen_coralnpu_wrapper.py — DO NOT hand-edit.\n")
    f.write("// Vyges integration wrapper for the CoralNPU autonomous compute island.\n")
    f.write("// V1.5 tie-off-first: device masters / debug / SPI / GPIO tied; DDR-mem\n")
    f.write("// AXI4 (256-bit) exported as m_axi_ddr_*; boot_addr in; wfi out.\n")
    f.write("// See socs/_ip/coralnpu-subsystem.yaml for the integration contract.\n\n")
    f.write("module coralnpu_island (\n")
    f.write(",\n".join(wports))
    f.write("\n);\n\n")
    f.write("  // rst_ni intentionally unused: %s has no reset port (internal POR /\n" % TOP)
    f.write("  // coralnpu-rst-sync). Kept on the wrapper for uniform clk/rst wiring.\n")
    f.write("  wire _unused_rst = rst_ni;\n\n")
    f.write("  %s u_coralnpu (\n" % TOP)
    lines = []
    for name, net in conns:
        if net == "":
            lines.append("    .%-44s ()" % name)
        else:
            lines.append("    .%-44s (%s)" % (name, net))
    f.write(",\n".join(lines))
    f.write("\n  );\n\nendmodule\n")

print("ports parsed: %d ; ddr exports: %d ; wrote %s" % (len(ports), len(ddr), OUT))
